language: python
python:
    - "3.6"
before_install:
    - pip install pytest pytest-cov
    - pip install codecov
script:
    - pytest --cov=./
env:
    - CODECOV_TOKEN=c91ef8c7-be59-4926-bb56-89cde16f2884
after_success:
    - codecov
