language: python
python:
    - "3.6"
before_install:
    - pip install pytest pytest-cov
    - pip install codecov
    - pip install matplotlib
    - pip install -i https://test.pypi.org/simple/ Exponentials-AD
script:
    - pytest --cov=./
env:
    - CODECOV_TOKEN=11a49e24-fc3d-4a95-9ef7-df2258d5babf
after_success:
    - codecov
