language: python
python:
    - "3.6"
before_install:
    - pip install pytest pytest-cov
    - pip install codecov
script:
    - pytest --cov=./
after_success:
    - bash <(curl -s https://codecov.io/bash) -t 6399b096-6237-477d-9c32-c2d6336ab841
