language: python
python:
    - "3.6"
before_install:
    - pip install pytest pytest-cov
    - pip install codecov
script:
    - pytest --cov=./
after_success:
    - bash <(curl -s https://codecov.io/bash) -t f17853b0-2b54-4bcf-852c-7a9e953fa7c9
